- id: "{{ site.url }}"
  title: "Lights Of Tuscany 2025"
  img: "img/Logo_Completo_LOT25.png"
  description: "Programme for international physics students in the VIRGO, LENS, INFN labs and Universities of Pisa and Florence"
  keywords: "aisf associazione italiana studenti di fisica iaps lot lights of tuscany pisa firenze lab visits"
